#!/usr/bin/python
#---------------------------------------------------------------------#
#_____________________________________________________________________#
#   ___                 _                 _       ____       ____     #
#  / _ \__   _____ _ __| | ___   __ _  __| |     |  _ \  ___/ ___|    #
# | | | \ \ / / _ \ '__| |/ _ \ / _` |/ _` |_____| | | |/ _ \___ \    #
# | |_| |\ V /  __/ |  | | (_) | (_| | (_| |_____| |_| | (_) |__) |   #
#  \___/  \_/ \___|_|  |_|\___/ \__,_|\__,_|     |____/ \___/____/    #
#                                                                     #
#            Developed by Chris Poole | @codingplanets  			  #
#		  https://github.com/codingplanets/Overload-DoS               #
#		          Version: 1.0                                        #
#_____________________________________________________________________#
#                      Overload-DoS installation                      #
#_____________________________________________________________________#
#                     chmod +x install-overload.py                    #
#                     sudo ./install-overload.py                      #
#_____________________________________________________________________#

import os, sys, time

if os.name == 'posix':
	c = os.system('which pip'); print "[+] pip is correctly installed"
	if c == 256:
		print "[+] Installing pip installer"; os.system('sudo yum install python-pip')
	else:
		pass
else:
	print '[+] Installing your pip installer'

try:
	import requests,colorama
	from termcolor import colored,cprint
except:
	try:
		if os.name == 'posix':
			os.system('sudo pip install colorama termcolor requests')
			sys.exit('[+] Overload has install the nessecary modules to execute program')
		elif os.name == 'nt':
			os.sytem('c:\python27\scripts\pip.exe install colorama requests termcolor')
			sys.exit('[+] Overload has install the nessecary modules to execute program')
		else:
			sys.exit('[+] Download and install all nessecary modules')
	except Exception,e:
		print '[-]',e
if os.name == 'nt':
	colorama.init()
